### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by JL2210** [Merith-TK/arch-pkg#2]
https://github.com/Merith-TK/arch-pkg/blob/cd0c784c15cb529440ced3ee7671b291a1bd154e/bin/wrap#L12
Please use `"$@"` instead of all these. It's better in a lot of ways.

**Comment by Merith-TK** [comment]
When I use $@, it captures the command. So when I send inputs, (aka `wrap
install nano`, when using $@, it reads `wrap wrap install nano` and then i
would have to program stuff in (stuff beyond my skill level) to sort out
the first command input,

Feel free to make a PR with your suggested edits. If they work for you, I
shall try it on my system with your edits in place.

**Comment by Merith-TK** [comment]
@JL2210 Please take a look at the beta branch, not released because i feel as if it can be improved.

**Comment by Merith-TK** [comment]
Fixed ( think ) In the beta build

**Comment by JL2210** [comment]
@Merith-TK Looks good.
