### ISSUE TITLE
Spurious 'else' causes error

### ISSUE THREAD

**Issue by JL2210** [Merith-TK/arch-pkg#6]
https://github.com/Merith-TK/arch-pkg/blob/37322f159076c498278fe4dc8a77af26c1d23445/bin/pkg#L52
This line causes an error.

**Comment by Merith-TK** [comment]
Yep, me at @rdtheriault noticed it, going to be edited out when i figure out a name other than pkg (as its already used by somethng in the AUR

**Comment by JL2210** [comment]
Try arch-pkg :).

**Comment by Merith-TK** [comment]
Alright, I just like the concept of short and simple things.

**Comment by JL2210** [comment]
apkg?

**Comment by Merith-TK** [comment]
I was honestly thinking `akg`. ANyways, im going to fix the issue brought up here, and rename it

**Comment by Merith-TK** [comment]
Fixed
